### ISSUE TITLE
Implement forced measurement outcome post-selection

### ISSUE THREAD

**Issue by cantwellc** [quantumlib/ReCirq#152]
Measurements in Quantum Chess occur during excluded or capture moves. The current Cirq implementation runs 100 samples to determine the measurement outcome when it encounters one of those move variants, then stores that outcome as part of the move sequence history. Future sampling runs are post-selected based on that outcome. 

In order to support features like undo move, sandbox mode demonstrations, and game replays, we need to allow the user to provide a desired measurement outcome through the REST API (currently implemented separately as a server that forwards calls to this Cirq implementation). The Cirq implementation of Quantum Chess should then use this value for the post-selection, instead of the random outcome from the 100-shot described above.

**Comment by losos0** [comment]
It was fixed by #167. Putting `.m0` in the notation works.
