### ISSUE TITLE
Cache split-jump for on demand consumption

### ISSUE THREAD

**Issue by cantwellc** [quantumlib/ReCirq#168]
If a split jump is from a fully occupied square to two empty squares, then the exact squares don't matter. We can pre-process a single split jump move and cache the result. Then any split jump can immediately return that result, and subsequently append the specific sub-circuit, with the correct qubit-square mapping, to the circuit that defines the quantum state.

**Comment by cantwellc** [comment]
The implementation of this will help with the design of the larger move caching system. The system as a whole should support caching of a number of "generic" moves, like this split jump, as well as moves specific to the current state.

**Comment by losos0** [comment]
This was done in #186.
