### ISSUE TITLE
Upgrade to Cirq 0.11

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/ReCirq#178]
- [x] ERROR: openfermion 1.0.1 has requirement cirq==0.10.0, but you'll have cirq 0.11.0 which is incompatible. https://github.com/quantumlib/OpenFermion/issues/736
- [x] If you plow ahead, it legitimately breaks because it requires the changes from https://github.com/quantumlib/OpenFermion/pull/727/ Merged May 12 but latest release is March 6. 
- [x] What's the difference between openfermion 1.0.0 and 1.0.1? There's no tag for the latter. edit: there's a tag now, but:
- [ ] ~~The tag for openfermion 1.0.1 points to the wrong commit.~~
- [x] PyTket breakage with cirq.Rx https://github.com/quantumlib/ReCirq/pull/182/ the updated test in this PR is blocked by pinning to Cirq 0.11, so we can't merge yet.
- [x] PyTket updates https://github.com/quantumlib/ReCirq/pull/182/
- [x] Can no longer load in cirq.TrialResult -- https://github.com/quantumlib/Cirq/issues/4318
- [x] cirq.TrialResult loading bugfix release with https://github.com/quantumlib/Cirq/pull/4319#issuecomment-885303444
- [x] Scipy removed `wrap_function` https://github.com/quantumlib/ReCirq/pull/184

**Comment by mpharrigan** [comment]
cc @dstrain115

**Comment by balopat** [comment]
I'm happy to release 0.11.1 with @MichaelBroughton soon

**Comment by balopat** [comment]
v0.11.1 is released

**Comment by mpharrigan** [comment]
Thanks @balopat and @MichaelBroughton

**Comment by mpharrigan** [comment]
We're now on 0.11!

**Comment by dstrain115** [comment]
Thanks so much for pushing this through!
