### ISSUE TITLE
quantum_board_test is slow

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/ReCirq#213]
This test module takes up 50% of total recirq unit test time on my computer. It's not excessive at this point, but I thought it would be worth asking if we could get the same coverage with less time.

@dstrain115 @cantwellc

**Comment by dstrain115** [comment]
Some of the bigger tests involve larger number of qubits (10-12 qubits or so), so we could potentially remove noisy simulations for those tests and/or try to reduce them even further.
