### ISSUE TITLE
docs/quantum_chess/concepts is pre-filled out. Is this necessary?

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/ReCirq#214]
docs/quantum_chess/concepts.ipynb is saved with its outputs. This means it won't get tested during regular doc builds. We usually only do this for notebooks where it is impractical to run them regularly. It looks like there is nothing preventing clearing the outputs on this notebook and letting the doc system build it.

Thoughts @dstrain115 @cantwellc ?

**Comment by dstrain115** [comment]
I don't think we need to save outputs for this notebook.  I could take a look at removing the outputs.
