### ISSUE TITLE
Use os.path.join in task filenames

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/ReCirq#31]
The `fn` attribute of tasks should use `os.path.join` instead of using a filename pattern that is incompatible with some operating systems.

**Comment by mpharrigan** [comment]
Can you give an example? `/` works on mac, linux, and windows.

**Comment by kevinsung** [comment]
Oh the example I had in mind was Windows, so I'm surprised it works. Doesn't Windows use the other kind of slash, `\` in file paths?

**Comment by mpharrigan** [comment]
Windows happily consumes either. I say we stick with `/` since it's easier to read

**Comment by kevinsung** [comment]
Ok but in principle there could be an operating system that doesn't accept `/`.

**Comment by mpharrigan** [comment]
In principle
