### ISSUE TITLE
Potential flake in quantum_chess `test_a10`

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/ReCirq#66]
See: 
https://github.com/quantumlib/ReCirq/runs/1042980828#step:6:395

**Comment by mpharrigan** [comment]
happened again https://github.com/quantumlib/ReCirq/runs/1051850929?check_suite_focus=true#step:6:395

**Comment by dstrain115** [comment]
Yeah, this is using the noisy simulator and it looks like it occasionally is not able to mitigate the noise.  I will fix it, but this week is crazy busy.  Do you want me to temporarily disable it for now?

Note that a few of the others probably have similar (but less likely problems).

**Comment by mpharrigan** [comment]
I'm fine just ignoring it for now
